.catalog:
  name: "DigitalOcean DNS"
  version: "v0.6.4"
  description: "Rancher External DNS service powered by DigitalOcean"
  minimum_rancher_version: v1.5.0
  maximum_rancher_version: v1.5.99
  questions:
    - variable: "DO_PAT"
      label: "DigitalOcean Personal Access Token"
      description: "Enter your personal access token"
      type: "string"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Domain Name"
      description: "The domain name managed by DigitalOcean."
      type: "string"
      required: true
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the domain) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false

digitalocean:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
