avi:
  image: avinetworks/avi-rancher-controller:2017-12-01T194110.475015629Z
  expose: 
   - 1000
  environment:
    AVI_USER: ${AVI_USER}
    AVI_PASSWORD: ${AVI_PASSWORD}
    AVI_CONTROLLER_ADDR: ${AVI_CONTROLLER_ADDR}
    AVI_CONTROLLER_PORT: ${AVI_CONTROLLER_PORT}
    AVI_SSL_VERIFY: ${AVI_SSL_VERIFY}
    AVI_CLOUD_NAME: ${AVI_CLOUD_NAME}
    AVI_DNS_SUBDOMAIN: ${AVI_DNS_SUBDOMAIN}
    AVI_TENANT: ${AVI_TENANT}
