version: '2'
catalog:
  name: Kafka
  version: 1.0.0-rancher2
  description: |
    Apache Kafka cluster.
  minimum_rancher_version: v0.59.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: kafka-0
  questions:
    - variable: "kafka_scale"
      description: "Number of brokers nodes. Note: Recommended an odd number"
      label: "Broker Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "kafka_mem"
      description: "Amount of memory to config brokers."
      label: "Broker Memory (mb):"
      required: true
      default: 1024 
      type: "string"
    - variable: "kafka_log_dir"
      description: "Broker volume to log data"
      label: "Broker log volume:"
      required: true
      default: "/opt/kafka/logs"
      type: "string"
    - variable: "kafka_log_retention"
      description: "Broker log retention in hours"
      label: "Broker log retention (h):"
      required: true
      default: "168"
      type: "int"
    - variable: "kafka_num_partitions"
      description: "Number of broker partitions"
      label: "Broker partitions:"
      required: true
      default: "1"
      type: "int"
    - variable: "kafka_delete_topics"
      label: "Delete topics:"
      description: |
        Enable delete topics in kafka.
      default: false
      required: true
      type: enum
      options:
        - false
        - true 
    - variable: "kafka_auto_create_topics"
      label: "Auto create topics:"
      description: |
        Enable auto create topics in kafka.
      default: true
      required: true
      type: enum
      options:
        - false
        - true
    - variable: "kafka_replication_factor"
      description: "Topics replication factor" 
      label: "Replication factor:"
      required: true
      default: 1 
      type: "int"
    - variable: "kafka_offset_retention_minutes"
      description: "Offset retention minutes" 
      label: "Offset retention:"
      required: true
      default: 1440 
      type: "int"
    - variable: "kafka_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable" 
      label: "Broker Interval (s):"
      required: true
      default: 60 
      type: "int"
    - variable: "kafka_adv_port"
      description: "Advertise port" 
      label: "Broker advertise port:"
      required: true
      default: 9092 
      type: "int"
    - variable: "kafka_pub_ip"
      description: "Advertise local and host public ip" 
      label: "Broker public ip:"
      required: false
      default: false 
      type: "boolean"
    - variable: host_label
      label: "Host Label"
      description: |
        Host label where deploy kafka. E.G.: 'kafka=true'
      required: false
      default: ""
      type: "string"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Kafka.
      label: "Zookeeper stack/service"
      default: "kafka-zk/zk"
      required: true
      type: "service"
services:
  broker:
    scale: ${kafka_scale}
    retain_ip: true
    health_check:
      port: ${kafka_adv_port}
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

