version: '2'
catalog:
  name: AWX
  version: 1.0-rancher1
  description: |
    Installs an AWX container, internal (Rancher) load-balancer, and an optional stack of tools AWX needs
  uuid: awx-rac-0
  questions:
    - variable: LB_LISTEN_PORT
      label: Load Balancer Listen Port
      description: |
        Specify a port for the Load Balancer to listen on (NOTE: AWS Web listens on 8052, but you can specify whatever port is available in your environment)
      type: int
      default: 8052
      required: true
    - variable: LB_LABEL_VALUE
      label: LoadBalancer host label
      description: |
        Enter a name=value pair of any required host label you may want in order to bind your load balancer to.
      default: lbhost=true
      type: string
    - variable: DATABASE_USERID
      label: Database UserID
      description: |
        Enter the userId you wish to use in order to connect to your PostgreSQL database
      type: string
      default: awx
      required: true
    - variable: DATABASE_PASSWORD
      label: Database Password
      description: |
        Enter the password you wish to use in order to connect to your PostgreSQL database
      type: string
      default: awxpass
      required: true
    - variable: DATABASE_NAME
      label: Database Name
      description: |
        Enter the name of the database that will be used in Postgres
      type: string
      default: awxdatabase
      required: true
    - variable: DATABASE_PORT
      label: Database port your PostgreSQL server listens on
      description: |
        This field is OPTIONAL if you are relying upon the internal PostgreSQL database this catalog item installs; or MANDATORY if you are providing your own.
      type: int
      default: 5432
      required: true
    - variable: SECRET_KEY
      label: Secret key used to secure communication between AWX_WEB and AWX_TASK containers
      description: |
        WARNING!!!! This field should be as globally unique as you can make it, such as a UUID generated by uuidgen.  This will help prevent your AWX server from being hijacked by unscrupulous people on the internet; if your server is exposed to the world.  Still, generate something SECURE!
      type: string
      default: someRandomSecretKey
      required: true
    - variable: POSTGRES_SERVER
      label: Postgres Server to use
      description: |
        Either select a Postgres server already installed in the environment, or leave this value at the default to let the catalog install it for you.
      type: service
      default: ""
    - variable: MEMCACHED_PORT
      label: The port Memcached listens on
      type: int
      default: 11211
      description: |
        This is an optional field if using the catalog installed version of Memcached.  If you are using your own server already installed, specify the port number here.
      required: true
    - variable: MEMCACHED_SERVER
      label: Memcached Server to use
      description: |
        Either select a Memcached server already installed in the environment, or leave this value at the default to let the catalog install it for you.
      type: service
      default: ""
    - variable: RABBITMQ_USER
      label: Enter the name of the RabbitMQ user
      description: |
        The RabbitMQ user is used to connect AWX to RabbitMQ so messages get routed properly.  This field is OPTIONAL if you are using the provided RabbitMQ server, or REQUIRED if you are providing your own server.
      type: string
      default: guest
      required: true
    - variable: RABBITMQ_PASSWORD
      label: Enter the password of the RabbitMQ user
      description: |
        The RabbitMQ password is used to connect AWX to RabbitMQ so messages get routed properly.  This field is OPTIONAL if you are using the provided RabbitMQ server, or REQUIRED if you are providing your own server.
      type: string
      default: guest
      required: true
    - variable: RABBITMQ_PORT
      label: Enter the name of the RabbitMQ user
      description: |
        The RabbitMQ port is used to connect AWX to RabbitMQ so messages get routed properly.  This field is OPTIONAL if you are using the provided RabbitMQ server, or REQUIRED if you are providing your own server.
      type: int
      default: 5672
      required: true
    - variable: RABBITMQ_VHOST
      label: Enter the VHOST name of the RabbitMQ user
      description: |
        The RabbitMQ VHOST name is used to connect AWX to RabbitMQ so messages get routed properly.  This field is OPTIONAL if you are using the provided RabbitMQ server, or REQUIRED if you are providing your own server.
      type: string
      default: awx
      required: true
    - variable: RABBITMQ_SERVER
      label: RabbitMQ Server to use
      description: |
        Either select a RabbitMQ server already installed in the environment, or leave this value at the default to let the catalog install it for you.
      type: service
      default: ""
    - variable: AWX_ADMIN_USER
      label: Specify an AWX Admin user
      description: |
        Specify the username to use as a default Administrator
      type: string
      default: admin
      required: true
    - variable: AWX_ADMIN_PASSWORD
      label: Specify an AWX Password
      description: |
        Specify the password to use for the new default Administrator
      type: string
      default: password
      required: true
    - variable: VOLUME_DRIVER
      label: Driver for volumes
      description: |
        How/Where to store your vault config and logs
      default: local
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs

services:
  awx-web:
    scale: 1
    start_on_create: true
  awx-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: awx-web
        source_port: ${LB_LISTEN_PORT}
        target_port: 8052
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  awx-task:
    scale: 1
    start_on_create: true
